### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by tkf** [JuliaLogging/ProgressLogging.jl#1]
Continuing discussion from: https://github.com/JunoLab/Juno.jl/issues/400

@pfitzseb Is there something you want to do before registering it?

* [x] Is name OK?  I just realized that the name crashes with @adamslc's [ProgressLogging.jl](https://github.com/adamslc/ProgressLogging.jl) although it's not registered.
* [x] Is API OK?  I have some suggestions but since this API is already out in the wild, I think releasing it as-is first makes sense.
* [x] Enable Documenter (see also https://github.com/JunoLab/ProgressLogging.jl/issues/3)
* [x] Write README https://github.com/JunoLab/ProgressLogging.jl/pull/4

**Comment by pfitzseb** [comment]
> Is name OK? I just realized that the name crashes with @adamslc's ProgressLogging.jl although it's not registered.

IMHO the name is fine (`ProgressBase.jl` could work too, but seems less descriptive).

>  Is API OK? I have some suggestions but since this API is already out in the wild, I think releasing it as-is first makes sense.

Agreed. Let's get this out in the current form and iterate over the API afterwards (ideally with deprecation warnings).

Would be good to have a minimal readme before registering, but apart from that this should be good to go.

**Comment by tkf** [comment]
> `ProgressBase.jl` could work too, but seems less descriptive

I thought about this too, but ProgressBase.jl sounds like a low-level package for package authors.  This package is likely to be used by end-users (e.g., in some scripts).  So I wanted something else.

> Would be good to have a minimal readme before registering

Good point. Will do.

This reminds me that it's also better to set up Documenter.  Can you do this?  I don't have access to the `⛭ Settings` tab.

**Comment by pfitzseb** [comment]
> I thought about this too, but ProgressBase.jl sounds like a low-level package for package authors.

I'd like to think of this package as something package authors use. I know @chrisrackauckas has been using `Juno.@progress` for a while. But yeah, let's just keep the current name.

> This reminds me that it's also better to set up Documenter. Can you do this? I don't have access to the ⛭ Settings tab.

Sure, will do.

**Comment by pfitzseb** [comment]
Alright, anything else we want to change before the first release?

**Comment by tkf** [comment]
The last concern for me is what to do with `@logprogress` API https://github.com/JunoLab/ProgressLogging.jl/issues/7#issuecomment-544660163

**Comment by tkf** [comment]
How about releasing after #11?

**Comment by tkf** [comment]
@JuliaRegistrator `register`

@pfitzseb Thanks for reviewing #11!

**Comment by tkf** [comment]
@JuliaRegistrator register

**Comment by pfitzseb** [comment]
Turns out JuliaRegistrator wasn't installed on the repo, so

@JuliaRegistrator register
