### ISSUE TITLE
Support for parallel maps?

### ISSUE THREAD

**Issue by juliohm** [JuliaLogging/ProgressLogging.jl#29]
I am considering the package for a simulation script. Does it already support parallel maps like the `progress_pmap` function from ProgressMeter.jl?

**Comment by tkf** [comment]
There is https://juliafolds.github.io/Transducers.jl/dev/manual/#Transducers.withprogress

```julia
using Transducers
tcollect(Map(f), withprogress(xs))
```

or equivalently

```julia
using ThreadsX
ThreadsX.map(f, withprogress(xs))
```

might work.  `withprogress` is also usable with Distributed.jl:

```julia
using Transducers
dcollect(Map(f), withprogress(xs))
```

They use ProgressLogging behind the scene.

**Comment by juliohm** [comment]
Nice, I should be using Transducers.jl instead of the lower level packages then. Is there a way to print variables in the loop with `dcollect(Map(f), withprogress(xs))`?

**Comment by tkf** [comment]
You can put `Map(x -> (@show(x); x))` anywhere in the transducer chain. Like

```julia
dcollect(Map(x -> (@show(x); x)) |> Filter(p) |> Map(f), withprogress(xs))
```

**Comment by juliohm** [comment]
Nice, will try to rewrite my scripts accordingly. :)
