### ISSUE TITLE
Fix Travis setup for PR

### ISSUE THREAD

**Issue by tkf** [JuliaLogging/ProgressLogging.jl#3]
@pfitzseb Do you know why the build is not triggered? https://travis-ci.com/JunoLab/ProgressLogging.jl/pull_requests

I'm seeing:
![image](https://user-images.githubusercontent.com/29282/67055674-e1f78d00-f0fd-11e9-8dd7-91483f82fbf0.png)

_Originally posted by @tkf in https://github.com/JunoLab/ProgressLogging.jl/pull/2#issuecomment-543412981_

**Comment by tkf** [comment]
OK, so it looks like this is because this package is the first one using https://travis-ci.com (not .org).  I requested the integration via https://travis-ci.com/organizations/JunoLab/repositories

**Comment by pfitzseb** [comment]
Travis seems to be running now.
