### ISSUE TITLE
Links to documentation in the README are broken

### ISSUE THREAD

**Issue by ForceBru** [JuliaLogging/ProgressLogging.jl#43]
Clicking the "docs" links in the README:

![docs_links](https://user-images.githubusercontent.com/8695383/126806001-c016b868-366f-4577-8f9a-4f1e04a03f8c.png)

leads to nonexistent URLs:
- stable: https://junolab.org/ProgressLogging.jl/stable
- dev: https://junolab.org/ProgressLogging.jl/dev

**Comment by pfitzseb** [comment]
Ah, I knew I forgot something. Fixed now (for dev, that is; stable will be fixed with the next release).
